export const intlLanguages = [
  { value: "English", label: "English" },
  { value: "Spanish", label: "Español" },
  { value: "French", label: "Français" },
  { value: "German", label: "Deutsch" },
  { value: "Italian", label: "Italiano" },
  { value: "Japanese", label: "日本語" },
  { value: "Korean", label: "한국어" },
  { value: "Portuguese", label: "Português" },
  { value: "Russian", label: "Русский" },
  { value: "Chinese", label: "中文" },
  { value: "Arabic", label: "العربية" },
  { value: "Dutch", label: "Nederlands" },
  { value: "Greek", label: "Ελληνικά" },
  { value: "Hindi", label: "हिन्दी" },
  { value: "Indonesian", label: "Bahasa Indonesia" },
  { value: "Polish", label: "Polski" },
  { value: "Swedish", label: "Svenska" },
  { value: "Turkish", label: "Türkçe" },
  { value: "Vietnamese", label: "Tiếng Việt" },
  { value: "Danish", label: "Dansk" },
  { value: "Norwegian", label: "Norsk" },
  { value: "Finnish", label: "Suomi" },
  { value: "Czech", label: "Čeština" },
  { value: "Hungarian", label: "Magyar" },
  { value: "Romanian", label: "Română" },
  { value: "Thai", label: "ไทย" },
  { value: "Ukrainian", label: "Українська" },
  { value: "Hebrew", label: "עברית" },
  { value: "Persian", label: "Farsi" },
];

export const intlLanguagesFormat = [
  { language: "English | English " },
  { language: "Spanish | Español" },
  { language: "French | Français " },
  { language: "German | Deutsch" },
  { language: "Italian | Italiano " },
  { language: "Japanese | 日本語" },
  { language: "Korean | 한국어 " },
  { language: "Portuguese | Português" },
  { language: "Russian | Русский" },
  { language: "Chinese | 中文" },
  { language: "Arabic | العربية" },
  { language: "Dutch | Nederlands" },
  { language: "Greek | Ελληνικά" },
  { language: "Hindi | हिन्दी" },
  { language: "Indonesian | Bahasa Indonesia" },
  { language: "Polish | Polski" },
  { language: "Swedish | Svenska" },
  { language: "Turkish | Türkçe" },
  { language: "Vietnamese | Tiếng Việt" },
  { language: "Danish | Dansk" },
  { language: "Norwegian | Norsk" },
  { language: "Finnish | Suomi" },
  { language: "Czech | Čeština" },
  { language: "Hungarian | Magyar" },
  { language: "Romanian | Română" },
  { language: "Thai | ไทย" },
  { language: "Ukrainian | Українська" },
  { language: "Hebrew | עברית" },
  { language: "Persian | Farsi" },
];
