export const intlLanguages = [
  { value: "English", label: "英语" },
  { value: "Spanish", label: "西班牙语" },
  { value: "French", label: "法语" },
  { value: "German", label: "德语" },
  { value: "Italian", label: "意大利语" },
  { value: "Japanese", label: "日语" },
  { value: "Korean", label: "韩语" },
  { value: "Portuguese", label: "葡萄牙语" },
  { value: "Russian", label: "俄语" },
  { value: "Chinese", label: "汉语" },
  { value: "Arabic", label: "阿拉伯语" },
  { value: "Dutch", label: "荷兰语" },
  { value: "Greek", label: "希腊语" },
  { value: "Hindi", label: "印地语" },
  { value: "Indonesian", label: "印度尼西亚语" },
  { value: "Polish", label: "波兰语" },
  { value: "Swedish", label: "瑞典语" },
  { value: "Turkish", label: "土耳其语" },
  { value: "Vietnamese", label: "越南语" },
  { value: "Danish", label: "丹麦语" },
  { value: "Norwegian", label: "挪威语" },
  { value: "Finnish", label: "芬兰语" },
  { value: "Czech", label: "捷克语" },
  { value: "Hungarian", label: "匈牙利语" },
  { value: "Romanian", label: "罗马尼亚语" },
  { value: "Thai", label: "泰语" },
  { value: "Ukrainian", label: "乌克兰语" },
  { value: "Hebrew", label: "希伯来语" },
  { value: "Persian", label: "波斯语" },
];

export const translateOptions = [
  { language: "English | 英语 " },
  { language: "Spanish | 西班牙语" },
  { language: "French | 法语 " },
  { language: "German | 德语" },
  { language: "Italian | 意大利语 " },
  { language: "Japanese | 日语" },
  { language: "Korean | 韩语 " },
  { language: "Portuguese | 葡萄牙语" },
  { language: "Russian | 俄语" },
  { language: "Chinese | 汉语" },
  { language: "Arabic | 阿拉伯语" },
  { language: "Dutch | 荷兰语" },
  { language: "Greek | 希腊语" },
  { language: "Hindi | 印地语" },
  { language: "Indonesian | 印度尼西亚语" },
  { language: "Polish | 波兰语" },
  { language: "Swedish | 瑞典语" },
  { language: "Turkish | 土耳其语" },
  { language: "Vietnamese | 越南语" },
  { language: "Danish | 丹麦语" },
  { language: "Norwegian | 挪威语" },
  { language: "Finnish | 芬兰语" },
  { language: "Czech | 捷克语" },
  { language: "Hungarian | 匈牙利语" },
  { language: "Romanian | 罗马尼亚语" },
  { language: "Thai | 泰语" },
  { language: "Ukrainian | 乌克兰语" },
  { language: "Hebrew | 希伯来语" },
  { language: "Persian | 波斯语" },
]
// export const intlLanguages = [
//   { value: "English", label: "English" },
//   { value: "Spanish", label: "Español" },
//   { value: "French", label: "Français" },
//   { value: "German", label: "Deutsch" },
//   { value: "Italian", label: "Italiano" },
//   { value: "Japanese", label: "日本語" },
//   { value: "Korean", label: "한국어" },
//   { value: "Portuguese", label: "Português" },
//   { value: "Russian", label: "Русский" },
//   { value: "Chinese", label: "中文" },
//   { value: "Arabic", label: "العربية" },
//   { value: "Dutch", label: "Nederlands" },
//   { value: "Greek", label: "Ελληνικά" },
//   { value: "Hindi", label: "हिन्दी" },
//   { value: "Indonesian", label: "Bahasa Indonesia" },
//   { value: "Polish", label: "Polski" },
//   { value: "Swedish", label: "Svenska" },
//   { value: "Turkish", label: "Türkçe" },
//   { value: "Vietnamese", label: "Tiếng Việt" },
//   { value: "Danish", label: "Dansk" },
//   { value: "Norwegian", label: "Norsk" },
//   { value: "Finnish", label: "Suomi" },
//   { value: "Czech", label: "Čeština" },
//   { value: "Hungarian", label: "Magyar" },
//   { value: "Romanian", label: "Română" },
//   { value: "Thai", label: "ไทย" },
//   { value: "Ukrainian", label: "Українська" },
//   { value: "Hebrew", label: "עברית" },
//   { value: "Persian", label: "Farsi" },
// ];

